apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      initContainers:
      - name: init-client
        image: alpine
        command: ["sh","-c", "apk add jq; jq -n env >> /usr/share/nginx/html/assets/env/application-config.json;"]
        volumeMounts:
        - name: volume-name
          mountPath: /usr/share/nginx/html/assets/env
      containers:
      - image: docker-kubernetes-tutorial/client
        imagePullPolicy: IfNotPresent
        name: dkb-client
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: volume-name
          mountPath: /usr/share/nginx/html/assets/env
      volumes:
      - name: volume-name
        emptyDir: {}