apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: node-env
  name: node-env
data:
  NODE_ENV: development

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                key: NODE_ENV
                name: node-env
          image: docker-kubernetes-tutorial/server
          name: dkb-server
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
          resources: {}

